### ISSUE TITLE
technical issue: "mark as done" and "next" buttons not working 

### ISSUE THREAD

**Issue by kmcneil901** [learn-co-curriculum/dsc-prework-intro#3]
Hello - I am working on the pre-work for the 8/7/23 live data science cohort. The "mark as done" and "next" buttons are not working on my end on the "Welcome to Prep!" and "The Structure of This Course" pages. The "previous" button is working. I have tried on two browsers. (https://learning.flatironschool.com/courses/7126/pages/welcome-to-prep?module_item_id=575405). Thanks for your time.

**Comment by jessepisel** [comment]
Thanks for opening this issue @kmcneil901 👋 . Do you have any adblockers running that might be interfering with these buttons? I am not able to replicate this issue in stock versions of chrome (v114.0.5735.198) or firefox (v115.0.2)

**Comment by kmcneil901** [comment]
it is now working. thank you for your time!
